version: "3.7"
services:
    reviews:
        build:
            context: ./
            dockerfile: Dockerfile-flask
            args:
                - version=1.0
                - project_id=${PROJECT_ID}
                - google_application_credentials=/home/reviews/credentials/gcp-key.json
                - gcp_bucket_name=sb-capstone-bucket
                - model_loader_class=GCPModelLoader
                - db_ip=${DB_IP}
#                - db_ip=35.247.24.229
        ports:
            - "5000:5000"
        volumes:
            # bind mount current directory
            - ./:/home/reviews
        image: capstone-service:latest

