#
# docker compose to build docker image to host API service locally
# this is a local development version of the container and will use volume mount
# with local directories so code is automatically updated on the server
#
version: "3.7"
services:
  reviews:
    build:
      context: ./
      dockerfile: Dockerfile-flask
      args:
        # API version number
        - version=1.0
        # IP address of MySQL database
        - db_ip=localhost
        # where models will be loaded - this can be relative path from /home/reviews or absolute path
        - model_dir=models
#        - sqlite_dir=/tmp # set this to /storage/<experiment name> for paperspace
        - db_type=mysql
    ports:
      - "5000:5000"
      - "3306:3306"
    volumes:
#      bind mount current directory
      - ./:/home/reviews
    # tag should match base tf image
    image: vtluk/capstone-paperspace:2.2.0rc2-py3


