#
# docker compose to build docker image to host API service locally
#
version: "3.7"
services:
  reviews:
    build:
      context: ./
      dockerfile: Dockerfile-flask-local
      args:
        - version=1.0
        - db_ip=localhost # IP address of MySQL database
        - model_dir=models # where models will be loaded
    ports:
      - "5000:5000"
      - "3306:3306"
    volumes:
      # bind mount current directory
      - ./:/home/reviews
      - ./models:/models
    image: capstone-service:latest
    command: -c "sleep 1d"  # keep the container running for debugging

