version: "3.7"
services:
    pyspark-jupyter:
        container_name: pyspark-juptyer
        build:
            context: ./
            dockerfile: Dockerfile-pyspark-jupyter
            args:
                - user=jupyter
                - old_user=jovyan
        volumes:
        # bind mount current directory
        - ../notebooks:/home/jupyter/work
        - ../dataset:/home/jupyter/dataset
        - ../util:/home/jupyter/util
        - ../models:/home/jupyter/models
        - ../reports:/home/jupyter/reports
        ports:
            - 8888:8888
            - 7077:7077
            - 8021:8021

# spark master port: 7077 - web ui port 8080
