version: "3.7"
services:
    pyspark-jupyter:
        build:
            context: ./
            dockerfile: Dockerfile-pyspark
            args:
                - user=pyspark
                - group=pyspark
                - spark_version=2.4.4
                - hadoop_version=2.7
                - conda_version=4.3.14
                #- conda_version=4.7.12.1
        ports:
            - 8888:8888
        volumes:
        # bind mount current directory
        - .:/home/jupyter
        - ../notebooks:/home/jupyter/notebooks
#        ports:
#            - "49152-65535:49152-65535"

